# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainbody.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(633, 438)
        MainWindow.setStyleSheet("background-color: rgb(228, 228, 228);\n"
"\n"
"background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 141, 641))
        self.widget.setMinimumSize(QtCore.QSize(141, 441))
        self.widget.setStyleSheet("background-color: rgb(88, 81, 139);\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0.04, stop:0 rgba(88, 81, 139, 234), stop:1 rgba(99, 128, 202, 255));")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(130, 0, 861, 641))
        self.widget_2.setStyleSheet("background-color: rgb(148, 177, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(90, 120, 199, 246), stop:1 rgba(255, 255, 255, 255));")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(30, 10, 381, 31))
        self.label.setStyleSheet("font: 87 italic 14pt \"Segoe UI Black\";")
        self.label.setObjectName("label")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(10, 50, 501, 591))
        self.widget_3.setMaximumSize(QtCore.QSize(501, 16777215))
        self.widget_3.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.widget_3.setObjectName("widget_3")
        self.button1 = QtWidgets.QPushButton(self.widget_3)
        self.button1.setGeometry(QtCore.QRect(30, 50, 421, 71))
        self.button1.setStyleSheet("background-color: rgb(147, 176, 254);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(183, 186, 195, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.button1.setObjectName("button1")
        self.button2 = QtWidgets.QPushButton(self.widget_3)
        self.button2.setGeometry(QtCore.QRect(30, 170, 421, 61))
        self.button2.setStyleSheet("background-color: rgb(147, 176, 254);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(183, 186, 195, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.button2.setObjectName("button2")
        self.button3 = QtWidgets.QPushButton(self.widget_3)
        self.button3.setGeometry(QtCore.QRect(30, 290, 421, 61))
        self.button3.setStyleSheet("background-color: rgb(147, 176, 254);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(183, 186, 195, 255), stop:1 rgba(255, 255, 255, 255));")
        self.button3.setObjectName("button3")
        self.widget_2.raise_()
        self.widget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "F A C U L T Y   S E L E C T I O N"))
        self.button1.setText(_translate("MainWindow", "Engineering"))
        self.button2.setText(_translate("MainWindow", "Environmental Design"))
        self.button3.setText(_translate("MainWindow", "Education"))
